### ISSUE TITLE
Use /30 for host network, not /31

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/packer-st2#40]
The use of a /31 prefix for the host network does not work on all operating systems. See https://github.com/StackStorm/st2docs/issues/744

This should be changed to /30.

**Comment by armab** [comment]
Good find!

How about a PR fixing that? The Vagrantfile is:

https://github.com/StackStorm/packer-st2/blob/5bb4125fc9f34a609a901916a163ce9176db917a/Vagrantfile.template#L42-L45
